var searchData=
[
  ['load_5freference_5fhaplotypes_0',['load_reference_haplotypes',['../input__prep_8cpp.html#a31b6160b69f849225374f36e12dab454',1,'load_reference_haplotypes(const std::string &amp;file_path, const savvy::genomic_region &amp;extended_reg, const savvy::genomic_region &amp;impute_reg, const std::unordered_set&lt; std::string &gt; &amp;subset_ids, std::vector&lt; target_variant &gt; &amp;target_sites, reduced_haplotypes &amp;typed_only_reference_data, reduced_haplotypes &amp;full_reference_data, genetic_map_file *map_file, float min_recom, float default_match_error):&#160;input_prep.cpp'],['../input__prep_8hpp.html#a31b6160b69f849225374f36e12dab454',1,'load_reference_haplotypes(const std::string &amp;file_path, const savvy::genomic_region &amp;extended_reg, const savvy::genomic_region &amp;impute_reg, const std::unordered_set&lt; std::string &gt; &amp;subset_ids, std::vector&lt; target_variant &gt; &amp;target_sites, reduced_haplotypes &amp;typed_only_reference_data, reduced_haplotypes &amp;full_reference_data, genetic_map_file *map_file, float min_recom, float default_match_error):&#160;input_prep.cpp']]],
  ['load_5freference_5fhaplotypes_5fold_5frecom_5fapproach_1',['load_reference_haplotypes_old_recom_approach',['../input__prep_8cpp.html#ae6103761cf74447b4a53fd6a17de447c',1,'load_reference_haplotypes_old_recom_approach(const std::string &amp;file_path, const savvy::genomic_region &amp;extended_reg, const savvy::genomic_region &amp;impute_reg, const std::unordered_set&lt; std::string &gt; &amp;subset_ids, std::vector&lt; target_variant &gt; &amp;target_sites, reduced_haplotypes &amp;typed_only_reference_data, reduced_haplotypes &amp;full_reference_data, genetic_map_file *map_file):&#160;input_prep.cpp'],['../input__prep_8hpp.html#ae6103761cf74447b4a53fd6a17de447c',1,'load_reference_haplotypes_old_recom_approach(const std::string &amp;file_path, const savvy::genomic_region &amp;extended_reg, const savvy::genomic_region &amp;impute_reg, const std::unordered_set&lt; std::string &gt; &amp;subset_ids, std::vector&lt; target_variant &gt; &amp;target_sites, reduced_haplotypes &amp;typed_only_reference_data, reduced_haplotypes &amp;full_reference_data, genetic_map_file *map_file):&#160;input_prep.cpp']]],
  ['load_5ftarget_5fhaplotypes_2',['load_target_haplotypes',['../input__prep_8cpp.html#a9de162b6e2c02f48cc2818b71cbf6f4c',1,'load_target_haplotypes(const std::string &amp;file_path, const savvy::genomic_region &amp;reg, std::vector&lt; target_variant &gt; &amp;target_sites, std::vector&lt; std::string &gt; &amp;sample_ids):&#160;input_prep.cpp'],['../input__prep_8hpp.html#a9de162b6e2c02f48cc2818b71cbf6f4c',1,'load_target_haplotypes(const std::string &amp;file_path, const savvy::genomic_region &amp;reg, std::vector&lt; target_variant &gt; &amp;target_sites, std::vector&lt; std::string &gt; &amp;sample_ids):&#160;input_prep.cpp']]],
  ['load_5fvariant_5fhmm_5fparams_3',['load_variant_hmm_params',['../input__prep_8cpp.html#ad0c14a19ad01f940f506c712b7c5b8ba',1,'load_variant_hmm_params(std::vector&lt; target_variant &gt; &amp;tar_variants, reduced_haplotypes &amp;typed_only_reference_data, float default_error_param, float recom_min, const std::string &amp;map_file_path):&#160;input_prep.cpp'],['../input__prep_8hpp.html#ad0c14a19ad01f940f506c712b7c5b8ba',1,'load_variant_hmm_params(std::vector&lt; target_variant &gt; &amp;tar_variants, reduced_haplotypes &amp;typed_only_reference_data, float default_error_param, float recom_min, const std::string &amp;map_file_path):&#160;input_prep.cpp']]],
  ['long_5foptions_5f_4',['long_options_',['../classgetopt__wrapper.html#a4cebd70eb91681f7486e7bacefd40aae',1,'getopt_wrapper']]],
  ['loo_5fdosage_5',['loo_dosage',['../classfull__dosages__results.html#a373933efa05ed63f213634bf955822c8',1,'full_dosages_results::loo_dosage(std::size_t i, std::size_t j)'],['../classfull__dosages__results.html#ac66cf8c846bb0327b35c6ef573e7b884',1,'full_dosages_results::loo_dosage(std::size_t i, std::size_t j) const']]],
  ['loo_5fdosages_5f_6',['loo_dosages_',['../classfull__dosages__results.html#a3c311392359ef32f7106caadcd6b3c60',1,'full_dosages_results']]]
];
