name: minimac4-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - bioconda::savvy=2.1.0
  - conda-forge::xz=5.8.1
  - conda-forge::zlib=1.2.13
  - bioconda::bcftools=1.21
  - conda-forge::doxygen=1.13.2
  - anaconda::graphviz=12.2.1
