name: minimac4-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - bioconda::savvy=2.1.0
  - conda-forge::xz=5.8.1
  - conda-forge::zlib=1.3.1
  - bioconda::bcftools=1.22
  - conda-forge::doxygen=1.9.5
